# Generated by Django 5.1.7 on 2025-03-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('retailer', 'Retailer'), ('consumer', 'Consumer')], default='farmer', max_length=20),
        ),
    ]
