# Generated by Django 5.1.7 on 2025-05-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0002_fooditem_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='batch_number',
            field=models.CharField(max_length=21, unique=True),
        ),
    ]
