# Generated by Django 5.1.7 on 2025-05-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0003_alter_fooditem_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='batch_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
